### PR TITLE
Fixed output in tests

### PR DESCRIPTION
**Pull request by delta-one**
Fixed an output in test-cases, when we still used `console.log` instead of `app.print`.

### CODE REVIEW

**Review by gusdebbaja — DISMISSED** [review]
looks good imo.

**Comment by delta-one** [comment]
Gonna try that again.

**Review by Seblerr — DISMISSED** [review]
Merge it.

**Review by ClickoBito — COMMENTED** [review]
Logout, and not logput as it says right now. Other then that it looks good, nothing weird going on :p

**Review by ClickoBito — APPROVED** [review]
Looks good

**Review by Seblerr — APPROVED** [review]

**Pull request merged**
