### PR TITLE
Javascript tests using mocha, chai, and supertest.

### PR DESCRIPTION
**Pull request by ClickoBito**
This branch implements some example tests using the mocha framework. Chai is used for verification using should. Supertest is used to test sending requests to the express server.

The tests are also executed automatically in Travis every time a new commit is pushed. The new Travis configuration includes setting up the database with resync and the data from load_testdata.

### CODE REVIEW

**Comment by delta-one** [comment]
1.) For some reason, a `git rebase` messes up the routes, even though you didn't change the file. This prevents the rebase.

2.) One slight problem with the setup as it is right now: The setup works for the Travis CI, but it's highly likely it won't work on your personal computer, because we've hardcoded the database for the test to use. We could either allow the user to create a local test-database and allow different usernames etc OR we run the test on the usual local database.

**Comment by ClickoBito** [comment]
@delta-one 

1.) I made some changes to the route index file, which I reverted. This is probably what causes the rebase errors. If we just use the github merge on the PR this should not cause any issues. I hope... 😃 

2.) Maybe I could change the settings so instead of based on env it could select the travis file if local doesn't exist.

**Comment by delta-one** [comment]
1.) Yes, simply merging everything into `development` seems to work fine.

2.) That sounds like a reasonable idea to get started. We can still decide later, if we need a dedicated database for testing.

**Comment by ClickoBito** [comment]
Calling this done. We might want to create a dedicated database for testing in the future but the current solution should be able to take care of all our needs

**Pull request merged**
