### PR TITLE
Switched to Sass

### PR DESCRIPTION
**Pull request by delta-one**
I switched to using Sass for the CSS-files. So far I've only copied some elements for the navbar and the footer into seperate files.

In order for this to work, you need to install Sass globally and modify your `nodemon`-command (if you're using it) - see README.md.

### CODE REVIEW

**Review by gusdebbaja — DISMISSED** [review]

**Review by Seblerr — APPROVED** [review]
Looks good to me, nice job.

**Comment by ClickoBito** [comment]
Would it be possible to install sass for the project instead of globally?

**Comment by delta-one** [comment]
We could install Sass as a `devDependency`. As guess it would be fine.

**Comment by ClickoBito** [comment]
I'd personally prefer having all dependancies as part of the project. But can't run the code right now so have to leave it to someone else to review and approve it.

**Comment by delta-one** [comment]
I can change it in the next PR. Just want to get this out of the way.

**Review by gusdebbaja — APPROVED** [review]

**Pull request merged**
