### PR TITLE
Fixed the contrast in createPatient form

### PR DESCRIPTION
**Pull request by Amaarillo**
Fixed the contrast in createPatient form (is redesigned now) and restructured it as well. I also restrcutured the doctor page and removed the layout.pug since it is not needed anymore to improve the consistency.

### CODE REVIEW

**Comment by delta-one** [comment]
Can't we put the header and the footer in a seperate file each, that we simply import in a template ?

**Comment by Amaarillo** [comment]
I think we can do that, I tried to do that first but got some issues doing that and it stopped me fixing the contrast of the createPatient page. Since I think it is more important to fix the design of the createpatient before the presentation, I restructured the code in this way temporarily to be able to proceed.  Maybe we can merge this one first and then create a new branch to put the header and footer in a separate file each because this branch "contrast" was made primarily to solve the contrast in createPatient.

**Comment by delta-one** [comment]
I'll approve the request, if that the next thing you do is split it into files.

It may work in our case, because we only have a couple of pages, but it's not a good solution and it's definitely not scalable.

**Comment by Amaarillo** [comment]
Ye, I agree and I will not do anything new in this branch so this is the last commit in this branch. But I will put a trello card for restructuring the code so we do not forget about it.

**Review by delta-one — APPROVED** [review]

**Review by Seblerr — APPROVED** [review]

**Pull request merged**
