### PR TITLE
Improved the general UX

### PR DESCRIPTION
**Pull request by Amaarillo**
This improved the design of admin page and changed the color of the mainbackground.

### CODE REVIEW

**Comment by delta-one** [comment]
I like the blue better than the greenish we had before. But maybe more people can give their opinion.

We could also think about including the navbar for the admin page and have a list of all users on the left for the admin.

**Comment by Seblerr** [comment]
I also prefer the blue theme more, fits better with the doctor page. 

Navbar being included in the admin page is certainly something we can have a look at.

**Comment by Amaarillo** [comment]
I agree with you that admin should get information about all users. Do you think we should do it in the same way as it is for doctor page?

**Comment by delta-one** [comment]
IMO it sounds reasonable to use the same kind of design for the admin, i.e. the userlist on the left and when you click on a user, you get the user's "profile" like we do with the patients. But maybe implement that step-wise. First merge this into `development` and then we can work on the admin-page.

**Pull request merged**
