### PR TITLE
Added logout-button for admins

### PR DESCRIPTION
**Pull request by delta-one**
Added a logout-button in the admin-template. It's the same button that we use for doctors and nurses.

### CODE REVIEW

**Comment by Amaarillo** [comment]
Very good, but I don't like where it is located. Maybe it would be better to place it inside the black window like the rest of the contents or something. It would be better if we make it fancier in some way because right now it is in the middle of nowhere (IMO).

**Comment by delta-one** [comment]
I'm really open to suggestions, but the problem with the admin-view right now is, that we don't have a navbar, but only the form. So wherever we place the button, it will look out of place. If you can think of a better spot, feel free to relocate the button.

**Comment by Amaarillo** [comment]
Maybe if we could have it located to the right-up corner like we did in the createPatient page with return-button. That is is the best suggestion that I can give which is a quick solution for that since we are short on time.

**Comment by Amaarillo** [comment]
What do you think?

**Comment by delta-one** [comment]
Then please do it. I can't find shit in the CSS code.

**Comment by Amaarillo** [comment]
Alright.

**Review by gusdebbaja — APPROVED** [review]
I ran it and I think that it is well-located.

**Comment by delta-one** [comment]
Looks fine to me.

**Review by Amaarillo — APPROVED** [review]

**Pull request merged**
