### PR TITLE
Added image to Nurse

### PR DESCRIPTION
**Pull request by delta-one**
Added image to nurses.

You'll have to resync the database.

### CODE REVIEW

**Review by gusdebbaja — APPROVED** [review]

**Review by gusdebbaja — APPROVED** [review]

**Comment by Amaarillo** [comment]
This looks good to me, but why did you change name from Brad to Melanie (just wondering since email is not consistent with the name)?

**Comment by delta-one** [comment]
Because it was much easier to find pictures of female nurses.

**Comment by Amaarillo** [comment]
Alright, I understand. You could change in the load_testdata from Brad to Melanie instead, but keep it consistent with the rest of the data before we merge this :D.

**Comment by delta-one** [comment]
If I do that, we have to go through all the approvals again.

**Comment by Amaarillo** [comment]
ok, nvm.

**Review by Amaarillo — APPROVED** [review]

**Comment by delta-one** [comment]
I don't mind changing it in a future PR.

**Comment by Amaarillo** [comment]
Ye, sounds good. Good job!

**Pull request merged**
